M48
; DRILL file {KiCad 9.0.7} date 2026-02-08T18:55:43+0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-08T18:55:43+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C3.400
%
G90
G05
T1
X170.3Y-86.0
T2
X59.5Y-67.65
X59.5Y-86.65
X135.5Y-60.65
X135.5Y-98.65
T3
X112.1Y-97.7
T4
X157.8Y-98.7
X170.3Y-98.7
M30
