M48
; DRILL file {KiCad 7.0.2} date Wed Apr 26 23:42:01 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-26T23:42:01+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1102
%
G90
G05
T1
X2.7087Y-2.7126
X2.7087Y-3.4606
X5.7008Y-2.4823
X5.7008Y-3.9921
T2
X4.7953Y-3.9528
T0
M30
